# coding: utf-8

"""
    Fief Administration API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.23.2
    Contact: contact@fief.dev
    Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

import six

from authmanager.infrastructure.fief.fiefapi.openapi_client.configuration import Configuration


class RoleCreate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'granted_by_default': 'bool',
        'permissions': 'list[str]'
    }

    attribute_map = {
        'name': 'name',
        'granted_by_default': 'granted_by_default',
        'permissions': 'permissions'
    }

    def __init__(self, name=None, granted_by_default=None, permissions=None,
                 local_vars_configuration=None):  # noqa: E501
        """RoleCreate - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._granted_by_default = None
        self._permissions = None
        self.discriminator = None

        self.name = name
        self.granted_by_default = granted_by_default
        self.permissions = permissions

    @property
    def name(self):
        """Gets the name of this RoleCreate.  # noqa: E501


        :return: The name of this RoleCreate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RoleCreate.


        :param name: The name of this RoleCreate.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def granted_by_default(self):
        """Gets the granted_by_default of this RoleCreate.  # noqa: E501


        :return: The granted_by_default of this RoleCreate.  # noqa: E501
        :rtype: bool
        """
        return self._granted_by_default

    @granted_by_default.setter
    def granted_by_default(self, granted_by_default):
        """Sets the granted_by_default of this RoleCreate.


        :param granted_by_default: The granted_by_default of this RoleCreate.  # noqa: E501
        :type: bool
        """
        if self.local_vars_configuration.client_side_validation and granted_by_default is None:  # noqa: E501
            raise ValueError("Invalid value for `granted_by_default`, must not be `None`")  # noqa: E501

        self._granted_by_default = granted_by_default

    @property
    def permissions(self):
        """Gets the permissions of this RoleCreate.  # noqa: E501


        :return: The permissions of this RoleCreate.  # noqa: E501
        :rtype: list[str]
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions):
        """Sets the permissions of this RoleCreate.


        :param permissions: The permissions of this RoleCreate.  # noqa: E501
        :type: list[str]
        """
        if self.local_vars_configuration.client_side_validation and permissions is None:  # noqa: E501
            raise ValueError("Invalid value for `permissions`, must not be `None`")  # noqa: E501

        self._permissions = permissions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RoleCreate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RoleCreate):
            return True

        return self.to_dict() != other.to_dict()
