version: '3.0'
services:
  postgres-test:
    container_name: postgres-test
    image: postgres:14.1-alpine
    volumes:
      - replica:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: "*"
    networks:
      - common-net
  postgres-test-replica-tests:
    container_name: postgres-test-replica-tests
    image: postgres:14.1-alpine
    env_file:
      - .env
    ports:
      - "54322:5432"
    environment:
      POSTGRES_HOST: "*"
      POSTGRES_DB: "cmms"
    networks:
      - common-net
  postgres-eventstore:
    container_name: postgres-eventstore
    image: postgres:14.1-alpine
    volumes:
      - eventstore:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - "5433:5432"
    environment:
      POSTGRES_HOST: "*"
    networks:
      - common-net

  be:
    image: sha256:99fe3e35a545a6fbaaa1e071dd975d5ee1cb44139399512cfd6037b112d34e23
    depends_on:
      - postgres-test
      - postgres-eventstore
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      POSTGRES_REPLICA_HOST: postgres-test
      POSTGRES_HOST: postgres-eventstore
      POSTGRES_PORT: 5432
      POSTGRES_REPLICA_PORT: 5432
    networks:
      - common-net
  fe:
    image: pumec/open_cmms:master
    ports:
      - "22222:22222"
    environment:
      BACKEND_URI: http://localhost:8080

  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
    networks:
      - common-net
  redmine:
    image: docker.io/bitnami/redmine:5
    ports:
      - '3000:3000'
    volumes:
      - 'redmine_data:/bitnami/redmine'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDMINE_USERNAME=user
      - REDMINE_PASSWORD=bitnami1
      - REDMINE_REST_API_ENABLED=1
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
      - REDMINE_DATABASE_USER=bn_redmine
      - REDMINE_DATABASE_NAME=bitnami_redmine
    networks:
      - common-net

volumes:
  eventstore:
  replica:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local

networks:
  common-net: {}