from enum import Enum

from pydantic import BaseModel


class AssetTelemetryType(str, Enum):
    AIR_TEMPERATURE = "AIR_TEMPERATURE",
    GROUND_TEMPERATURE = "GROUND_TEMPERATURE",
    ROAD_TEMPERATURE = "ROAD_TEMPERATURE",
    VISIBILITY = "VISIBILITY",
    WIND_SPEED = "WIND_SPEED",
    WIND_DIRECTION = "WIND_DIRECTION",
    RAINFALL_INTENSITY = 'RAINFALL_INTENSITY'
    WIND_GUST_SPEED = "WIND_GUST_SPEED",
    WIND_GUST_DIRECTION = "WIND_GUST_DIRECTION",
    AIR_PRESSURE = "AIR_PRESSURE",
    AIR_HUMIDITY = "AIR_HUMIDITY",
    ROAD_WARNING_STATUS = "ROAD_WARNING_STATUS",
    ROAD_RAIN_STATUS = "ROAD_RAIN_STATUS",
    ROAD_SURFACE_STATUS = "ROAD_SURFACE_STATUS",
    GRIP = "GRIP"
    WATER_HEIGHT = "WATER_HEIGHT"
    SNOW_HEIGHT = "SNOW_HEIGHT"
    ICE_HEIGHT = "ICE_HEIGHT"


class AssetTelemetryValue(str, Enum):
    CELSIUS = "CELSIUS",
    METER_PER_SECOND = "METER_PER_SECOND",
    MILIMETERS = "MILIMETERS"
    METERS = "METERS",
    CIRCLE_DEGREES = "CIRCLE_DEGREES",
    MILLIMETER_PER_SECOND = "MILLIMETER_PER_SECOND",
    HECTO_PASCAL = "HECTO_PASCAL",
    PERCENTAGE = "PERCENTAGE",
    STRING = 'STRING'



class AssetTelemetry(BaseModel):
    type: AssetTelemetryType
    value: AssetTelemetryValue
