"""migration name

Revision ID: c51f60311919
Revises: 9d1fedf47860
Create Date: 2022-11-20 20:14:16.806822

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c51f60311919'
down_revision = '9d1fedf47860'
branch_labels = None
depends_on = None


def upgrade() -> None:
    print("aaa")
    # ### commands auto generated by Alembic - please adjust! ###
    enum = postgresql.ENUM('OPEN', 'READY', 'DONE', 'REMOVED', name='taskstate')
    enum.create(op.get_bind(), checkfirst=True)
    enumtasktype = postgresql.ENUM('COMPONENT_CHANGE', 'LOCAL_INSPECTION', name='tasktype')
    enumtasktype.create(op.get_bind(), checkfirst=True)
    op.create_table('tasks',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('task_state', enum, nullable=False),
    sa.Column('task_type', enumtasktype, nullable=False),
    sa.Column('station_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_station_id'), 'tasks', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_station_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
