"""migration name

Revision ID: 65268a7424b5
Revises: a0c68f816b76
Create Date: 2022-11-13 15:53:56.600108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65268a7424b5'
down_revision = 'a0c68f816b76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    enum = postgresql.ENUM('AWAITING', 'INSTALLED', 'WILL_BE_REMOVED', 'REMOVED', name='assigned_component_status')
    enum.create(op.get_bind(), checkfirst=True)
    op.add_column('assigned_component', sa.Column('assigned_component_status', enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assigned_component', 'assigned_component_status')
    # ### end Alembic commands ###
