"""migration name

Revision ID: a0c68f816b76
Revises: b9f2950f290a
Create Date: 2022-11-07 13:37:08.502602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0c68f816b76'
down_revision = 'b9f2950f290a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigned_component',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('station_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('asset_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assigned_component_asset_id'), 'assigned_component', ['asset_id'], unique=False)
    op.create_index(op.f('ix_assigned_component_id'), 'assigned_component', ['id'], unique=False)
    op.create_index(op.f('ix_assigned_component_station_id'), 'assigned_component', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assigned_component_station_id'), table_name='assigned_component')
    op.drop_index(op.f('ix_assigned_component_id'), table_name='assigned_component')
    op.drop_index(op.f('ix_assigned_component_asset_id'), table_name='assigned_component')
    op.drop_table('assigned_component')
    # ### end Alembic commands ###
