"""migration name

Revision ID: 0a9a8b9ea89a
Revises: 4caa421b0d4f
Create Date: 2023-04-21 23:29:06.678078

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0a9a8b9ea89a'
down_revision = '4caa421b0d4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('road_segment', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('road_segment', 'is_active')
    # ### end Alembic commands ###
