"""migration name

Revision ID: 0d4ba5b8d9c1
Revises: 05b8c9b14058
Create Date: 2023-04-03 21:45:23.992996

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d4ba5b8d9c1'
down_revision = '05b8c9b14058'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redmine_tasks',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('redmine_id', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('redmine_tasks')
    # ### end Alembic commands ###
