"""migration name

Revision ID: 1235898d1af0
Revises: a76de7670bbb
Create Date: 2023-08-20 17:15:34.661203

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1235898d1af0'
down_revision = 'a76de7670bbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_contracts',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('created_at', sa.Date(), nullable=False),
                    sa.Column('valid_from', sa.Date(), nullable=False),
                    sa.Column('valid_until', sa.Date(), nullable=False),
                    sa.Column('identifier', sa.String(), nullable=False),
                    sa.Column('warranty_period_days', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_investment_contracts_id'), 'investment_contracts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investment_contracts_id'), table_name='investment_contracts')
    op.drop_table('investment_contracts')
    # ### end Alembic commands ###
