"""migration name

Revision ID: a78413a57fba
Revises: 0a9a8b9ea89a
Create Date: 2023-07-05 22:54:09.259095

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a78413a57fba'
down_revision = '0a9a8b9ea89a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("delete from issues")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('station_name', sa.String(), nullable=False))
    op.add_column('issues', sa.Column('road_segment_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('issues', sa.Column('road_segment_name', sa.String(), nullable=False))
    op.add_column('issues', sa.Column('is_external', sa.BOOLEAN(), nullable=False))
    op.alter_column('issues', 'station_id',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'station_id',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_column('issues', 'is_external')
    op.drop_column('issues', 'road_segment_name')
    op.drop_column('issues', 'road_segment_id')
    op.drop_column('issues', 'station_name')
    # ### end Alembic commands ###
