"""migration name

Revision ID: 51ba85432f2b
Revises: aa2454aa15ac
Create Date: 2023-02-04 14:49:40.704530

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51ba85432f2b'
down_revision = 'aa2454aa15ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets_telemetry',
                    sa.Column('asset_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('telemetry_type',
                              sa.Enum('AIR_TEMPERATURE', 'GROUND_TEMPERATURE', 'ROAD_TEMPERATURE', 'VISIBILITY',
                                      'WIND_SPEED', 'WIND_DIRECTION', 'RAINFALL_INTENSITY', 'WIND_GUST_SPEED',
                                      'WIND_GUST_DIRECTION', 'AIR_PRESSURE', 'AIR_HUMIDITY', name='assettelemetrytype'),
                              nullable=False),
                    sa.Column('telemetry_value',
                              sa.Enum('CELSIUS', 'METER_PER_SECOND', 'CIRCLE_DEGREES', 'MILLIMETER_PER_SECOND',
                                      'HECTO_PASCAL', 'PERCENTAGE', name='assettelemetryvalue'), nullable=False),
                    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
                    sa.PrimaryKeyConstraint('asset_id', 'telemetry_type', 'telemetry_value')
                    )
    op.create_index(op.f('ix_assets_telemetry_asset_id'), 'assets_telemetry', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_telemetry_asset_id'), table_name='assets_telemetry')
    op.drop_table('assets_telemetry')
    # ### end Alembic commands ###
