"""migration name

Revision ID: ac7f3723dac7
Revises: 0d4ba5b8d9c1
Create Date: 2023-04-11 02:22:03.236309

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac7f3723dac7'
down_revision = '0d4ba5b8d9c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('subject', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('user', sa.String(), nullable=False),
                    sa.Column('station_id', sa.String(), nullable=True),
                    sa.Column('component_id', sa.String(), nullable=True),
                    sa.Column('active', sa.BOOLEAN(), nullable=False),
                    sa.Column('created_on', postgresql.TIMESTAMP(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issues')
    # ### end Alembic commands ###
