"""migration name

Revision ID: 879f3898e70f
Revises: f5265e2d93bf
Create Date: 2023-02-21 00:24:22.263866

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '879f3898e70f'
down_revision = 'f5265e2d93bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('km_of_road', sa.FLOAT(), nullable=True))
    op.add_column('station', sa.Column('km_of_road_note', sa.String(), nullable=False))
    op.add_column('station', sa.Column('latitude', sa.FLOAT(), nullable=True))
    op.add_column('station', sa.Column('longitude', sa.FLOAT(), nullable=True))
    op.add_column('station', sa.Column('see_level', sa.INTEGER(), nullable=True))
    op.add_column('station', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station', 'description')
    op.drop_column('station', 'see_level')
    op.drop_column('station', 'longitude')
    op.drop_column('station', 'latitude')
    op.drop_column('station', 'km_of_road_note')
    op.drop_column('station', 'km_of_road')
    # ### end Alembic commands ###
