"""migration name

Revision ID: b851e447cba6
Revises: 879f3898e70f
Create Date: 2023-02-28 11:20:09.253139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b851e447cba6'
down_revision = '879f3898e70f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('legacy_ids', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station', 'legacy_ids')
    # ### end Alembic commands ###
