"""migration name

Revision ID: aa2454aa15ac
Revises: 2477edaad5f1
Create Date: 2023-01-31 09:08:19.855674

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'aa2454aa15ac'
down_revision = '2477edaad5f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_component', sa.Column('warranty_period_days', sa.INTEGER(), nullable=True))
    op.add_column('assigned_component', sa.Column('warranty_period_until', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assigned_component', 'warranty_period_until')
    op.drop_column('assigned_component', 'warranty_period_days')
    # ### end Alembic commands ###
