# This is a basic workflow to help you get started with Actions

name: BE tests

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - *


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./backend/docker-compose.yml
          services: |
            postgres-test-replica-tests
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r ./backend/requirements-dev.txt

      - name: Run Tests
        working-directory: ./backend/test
        run: pytest

