name: Automatic Rebase
on:
    release:
        types: [created]
jobs:
    rebase:
        name: Rebase
        runs-on: ubuntu-latest
        steps:
            - name: Mark version as ready to deleted
              run: |
                echo ${GITHUB_REF#refs/tags/}
