name: Automatic Rebase
on:
    release:
        types: [deleted]
jobs:
    rebase:
        name: Rebase
        runs-on: ubuntu-latest
        steps:
            - name: Mark version as ready to deleted
              run: |
                echo ${{refs/tags/<tag_name>}}
